name: dr_shahin_uk
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.1
  # firebase_storage: ^13.0.0   # ❌ Removed since using Cloudinary
  file_picker: ^10.3.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  http: ^1.2.2
  cloudinary_flutter: ^0.9.0
  cloudinary_sdk: ^4.0.1
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  logging: ^1.1.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http_parser: ^4.1.2
  path: ^1.9.1
  flutter_local_notifications: ^19.4.2
  cloud_functions: ^6.0.4
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  # ✅ Added here

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpeg"  # ✅ Make sure this file exists

flutter:
  uses-material-design: true
  assets:
    - assets/images/
